Repository Moulayli/DAO, pull requests merged in 2023-04, with the labels that each got.

#1 CLI menu + branch history fix
  src/main/java/dao/DaoMain.java
  src/main/java/dao/dao/JdbcSingleton.java
  src/main/java/dao/dao/UserDAO.java
  src/main/java/dao/gui/Locale.java
  src/main/java/dao/gui/Menu.java
  src/main/java/dao/model/User.java
  target/classes/META-INF/MANIFEST.MF
  target/classes/META-INF/maven/com.digi.m02/dao3/pom.properties
  target/classes/META-INF/maven/com.digi.m02/dao3/pom.xml
  target/classes/dao/DaoMain.class
  target/classes/dao/dao/IDAO.class
  target/classes/dao/dao/JdbcSingleton.class
  target/classes/dao/dao/UserDAO.class
  target/classes/dao/gui/Locale.class
  target/classes/dao/gui/Menu.class
  target/classes/dao/model/User.class
Labels: bug, enhancement

#3 GUI
  .classpath
  pom.xml
  src/main/java/dao/DaoMain.java
  src/main/java/dao/dao/JdbcSingleton.java
  src/main/java/dao/dao/UserDAO.java
  src/main/java/dao/gui/Locale.java
  src/main/java/dao/gui/Menu.java
  src/main/java/dao/model/User.java
  target/classes/dao/DaoMain.class
  target/classes/dao/dao/IDAO.class
  target/classes/dao/dao/JdbcSingleton.class
  target/classes/dao/dao/UserDAO.class
  target/classes/dao/gui/Locale.class
  target/classes/dao/gui/Menu.class
  target/classes/dao/model/User.class
Labels: enhancement

#4 Crud
  src/main/java/dao/dao/IDAO.java
  src/main/java/dao/dao/JdbcSingleton.java
  src/main/java/dao/dao/UserDAO.java
  target/classes/dao/DaoMain.class
  target/classes/dao/dao/IDAO.class
  target/classes/dao/dao/JdbcSingleton.class
  target/classes/dao/dao/UserDAO.class
  target/classes/dao/gui/Locale.class
  target/classes/dao/gui/Menu.class
  target/classes/dao/model/User.class
Labels: documentation

#7 Merge develop on master
  .classpath
  pom.xml
  src/main/java/dao/DaoMain.java
  src/main/java/dao/dao/IDAO.java
  src/main/java/dao/dao/JdbcSingleton.java
  src/main/java/dao/dao/UserDAO.java
  src/main/java/dao/gui/Locale.java
  src/main/java/dao/gui/Menu.java
  src/main/java/dao/model/User.java
  target/classes/META-INF/MANIFEST.MF
  target/classes/META-INF/maven/com.digi.m02/dao3/pom.properties
  target/classes/META-INF/maven/com.digi.m02/dao3/pom.xml
  target/classes/dao/DaoMain.class
  target/classes/dao/dao/IDAO.class
  target/classes/dao/dao/JdbcSingleton.class
  target/classes/dao/dao/UserDAO.class
  target/classes/dao/gui/Locale.class
  target/classes/dao/gui/Menu.class
  target/classes/dao/model/User.class
Labels: enhancement
